version: '3'
services:
    db:
        image: mariadb
        volumes:
            #- db:/var/lib/mysql
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_DATABASE: DATABASE
            MYSQL_USER: USER
            MYSQL_PASSWORD: USER_PASSWORD
        networks:
            - backend
        ports:
            - XXXX:3306
        deploy:
            restart_policy: 
                condition: on-failure
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M

    server:
        depends_on:
            - db
        image: SERVER
        volumes: 
            #- server:/server
            - ./server:/server
        networks:
            - backend
            - frontend
        ports: 
            - XXXX:3000
        deploy:
            restart_policy: 
                condition: on-failure
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M

    client:
        depends_on:
            - db
            - server
        image: CLIENT
        volumes: 
            #- client:/client
            - ./client:/client
        networks:
            - frontend
        ports:
            - XXXX:8080
        deploy:
            #restart_policy:
                #condition: on-failure
            resources:
                limits:
                    cpus: "0.5"
                    memory: 512M

networks:
    backend:
    frontend:
#volumes: 
    #db:
    #server:
    #client:
